### ISSUE TITLE
Text field also should be "Add a new task to To-Do"

### ISSUE THREAD

**Issue by indu173** [indu173/WebApp#4]
![image](https://github.com/user-attachments/assets/191965ea-c802-4ba7-bc56-590bed515ed4)
![image](https://github.com/user-attachments/assets/9e330c71-afb4-4d9d-b8b0-61ecf1e81e48)

Text field also should be "Add a new task to To-Do"

**Comment by GeviReddy** [comment]
ok i will fix it
